### ISSUE TITLE
EVI outputs wrong probabilities

### ISSUE THREAD

**Issue by RenatoGeh** [Juice-jl/ProbabilisticCircuits.jl#107]
Hi,

Here's a MWE (up-to-date with both `master` branches of PCs and LCs):

```julia
# Utility function to create literals
f(x) = PlainProbLiteralNode.(Int32.([-x, x]))
# Bernoulli parameters
W = map(x -> log.(x), [[.6, .4], [.5, .5], [.5, .5], [.8, .2]])
# Bernoulli nodes
A1, A2, B1, B2 = PlainSumNode.(f.([1, 1, 2, 2]), W)
# Products
P1, P2 = PlainMulNode.([[A1, B1], [A2, B2]])
# Root
C = PlainSumNode([P1, P2], log.([.2, .8]))

# Produce all possible assignments with two binary variables
D = DataFrame(all_valuations(1:2), :auto)

# Compute the EVI.
display(exp.(EVI(C, D)))
4-element Vector{Float64}:
 0.0032000000000000015
 0.004799999999999999
 0.012800000000000008
 0.0192

# Probabilities don't add up to one?

# Compute the MAR over the same complete assignments. Should be the same:
display(exp.(MAR(C, D)))
4-element Vector{Float32}:
 0.12
 0.14
 0.35999998
 0.38

# Showing the right probabilities.
```

Interestingly, from the few examples I tested on my machine, this seems to only affect non-deterministic PCs. Granted, I haven't thoroughly examined the code yet to say this is a certainty. I'll take a look at it now and try to find a fix for this issue.

As a side note, it would perhaps be nice to have some in-code documentation. As it is, the code is very intimidating and kind of obfuscated (for me, at least). Helps with contributing to Juice. :)

Thanks

**Comment by khosravipasha** [comment]
Thanks for the bug report, interesting we used to have a test to check EVI==MAR for full data. Maybe it was not catching this
scenario. We usually just call MAR even on full data so probably that's why we did not notice.

I will take a closer look into this example. 

Also note that we are working on refactoring the library and there is some big changes for version 0.4, and EVI and MAR are being rewritten specially the gpu versions.

> As a side note, it would perhaps be nice to have some in-code documentation. As it is, the code is very intimidating and kind of obfuscated (for me, at least). Helps with contributing to Juice. :)
Yesh the new version is less complicated and much cleaner, will add some more docs there :)

**Comment by guyvdbroeck** [comment]
I think EVI is not supposed to be run on non deterministic circuits. It's essentially a faster version of MAR for when data and circuit have no latents

**Comment by RenatoGeh** [comment]
> Yesh the new version is less complicated and much cleaner, will add some more docs there :)

Good to know! Looking forward to this new version.

> I think EVI is not supposed to be run on non deterministic circuits. It's essentially a faster version of MAR for when data and circuit have no latents

I see. Is this set to change after the refactor? If not, perhaps it might be a good idea to add a note referencing this to both the [EVI manual entry](https://juice-jl.github.io/ProbabilisticCircuits.jl/dev/manual/queries/#Full-Evidence-(EVI)) and [`EVI` docs](https://juice-jl.github.io/ProbabilisticCircuits.jl/dev/api/internals/probabilistic_circuits/#ProbabilisticCircuits.EVI).

**Comment by khosravipasha** [comment]
Current implementation of EVI is going to be gone probably, so both MAR and EVI will call the same function `loglikelihoods`.

**Comment by khosravipasha** [comment]
The next API for queries in `v0.4` will be something like this, for example can compute `loglikelihoods` as follows (this handles both cases of having missing values (marginals) and having no missing values (EVI)). So both doing either EVI or MAR you can call `loglikelihoods`. We are still finishing porting some stuff so not everything is done. More documentation and examples for other queries will be out when we release v0.4 (soon hopefully).

[CPU version](https://juice-jl.github.io/ProbabilisticCircuits.jl/dev/api/internals/probabilistic_circuits/#ProbabilisticCircuits.loglikelihoods-Tuple{ProbCircuit,%20Matrix{T}%20where%20T}):, we use missing to denote missing values, so the data would be type of `Array{Union{Missing, ...}}`.
```julia
loglikelihoods(pc::ProbCircuit, data::Matrix)
```

[GPU version:](https://juice-jl.github.io/ProbabilisticCircuits.jl/dev/api/internals/probabilistic_circuits/#ProbabilisticCircuits.loglikelihoods-Tuple{ProbabilisticCircuits.CuBitsProbCircuit,%20CUDA.CuArray}) 
similary type of data is `CuArray{Union{Missing, ...}}`
```julia
loglikelihoods(bpc::CuBitsProbCircuit, data::CuArray; batch_size)
```

**Comment by zevereir** [comment]
I don't know if this is still relevant, but I got a related error. I try to combine 2 circuits scaled with weights. In the test case, the two circuits are equal and the weights sum up to 1, which would lead to the EVI of the combination to be equal to the EVI of one of the circuits. As can be seen below, this is not the case. 

`function test1()
   a,b,c,d= pos_literals(ProbCircuit, 4)
    c1=0.3*b+0.7*(-b)
    c2=0.4*b+0.6*(-b)
    ac1=a*c1
    ac2=(-a)*c2
    combined= 0.8*ac1+0.2*ac2
    return combined
end

function test2()
    a,b,c,d= pos_literals(ProbCircuit, 4)
    c1=0.3*b+0.7*(-b)
    c2=0.4*b+0.6*(-b)
    ac1=a*c1
    ac2=(-a)*c2
    combined= 0.8*ac1+0.2*ac2
    return combined
end

jpt1=exp.(MAR(test1(),all_models))
jpt2=exp.(MAR(test2(),all_models))
new_net=0.5*test1()+0.5*test2()
jpt_evi=exp.(EVI(new_net,all_models))
jpt_mar=exp.(MAR(new_net,all_models))
for x in 1:length(jpt1)
    println("\n ", all_models[x,:], " ", jpt1[x], " ", jpt2[x], " ", jpt_mar[x], " ", jpt_evi[x])
end
`
![image](https://user-images.githubusercontent.com/26394037/205036387-1a80c2b0-fc14-4bfb-8be3-d680b45a687e.png)


Using MAR (the 4the number here) solves this issue, but when I use it on a different setup, I always get OutOfMemory-errors, even though the circuits have 20 nodes. 

`
function net1()
    a,b,c,d = pos_literals(ProbCircuit, 4)

    full_c_b=0.3*c+0.7*(-c)
    full_c_neg_b=0.8*c+0.2*(-c)
    b_a_1=b*full_c_b
    b_a_2=(-b)*full_c_neg_b

    full_b_a=0.6*b_a_1+0.4*b_a_2


    full_b_neg_a=0.5*b_a_1+0.5*b_a_2
    a1=a*full_b_a
    a2=(-a)*full_b_neg_a
    full_a=0.25*a1+0.75*a2

    return full_a
end
print(exp.(MAR(net1(),all_models)))
`

![image](https://user-images.githubusercontent.com/26394037/205036999-30a2ff08-ebbd-4ff4-9ca3-b85bc391f951.png)


thanks for looking into this!

Sieben
