### ISSUE TITLE
Save a Prob/Logistic circuit without vtree

### ISSUE THREAD

**Issue by YitaoLiang** [Juice-jl/ProbabilisticCircuits.jl#20]

**Comment by khosravipasha** [comment]
Also these two related from logic circuits, probably same solution works:

https://github.com/Juice-jl/LogicCircuits.jl/issues/12

https://github.com/Juice-jl/LogicCircuits.jl/issues/8

**Comment by khosravipasha** [comment]
Tracking in https://github.com/Juice-jl/LogicCircuits.jl/issues/12
