### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by khosravipasha** [Juice-jl/ProbabilisticCircuits.jl#3]
This is due to one of the dependencies "BlossomV".  More info here: https://github.com/mlewe/BlossomV.jl/issues/12

**Comment by khosravipasha** [comment]
Options are:
1. Remove Blossom as dependecy
2. Use @require or some sort of optional dependency in julia (a bit hacky)

**Comment by guyvdbroeck** [comment]
closed by https://github.com/Juice-jl/ProbabilisticCircuits.jl/commit/64c3004e1b8dd21c49170ce3ff3d48bf3b642b69
