### ISSUE TITLE
Batching Support for queries

### ISSUE THREAD

**Issue by khosravipasha** [Juice-jl/ProbabilisticCircuits.jl#30]
Some queries don't fully support batching/batch sizes yet:

- [x] MAR
- [x] estimate_parameters_em
- [x] EVI
- [x] log_likelihood
- [x] estimate_parameters
- [x] estimate_parameters_em
- [x] Sampling (not direclyt related, but allow batch size maybe; users can do it themselves too)
- [x] MAP inference

**Comment by khosravipasha** [comment]
`estimate_parameters_em` seems to not do the batching. It seems it does not do batching even if given batched data, here's minimal code to reproduce:

Even if I lower batch_size (10 for example) it still tries to allocate 4.118GB on gpu. I guess somewhere batching is not done.

```
using LogicCircuits
using ProbabilisticCircuits
using DataFrames

pc = zoo_psdd("plants.psdd")
data, _, _ = twenty_datasets("plants")

println("Load a circuit with $(num_nodes(pc)) nodes and $(num_parameters(pc)) parameters.")
println("Load a data with $(num_features(data)) features and $(num_examples(data)) examples.")

data_miss = make_missing_mcar(data; keep_prob=0.7)

gpu_data_miss = to_gpu(batch(data_miss, 1024));
params_gpu = estimate_parameters_em(pc, gpu_data_miss;pseudocount=1.0);
```

**Comment by liuanji** [comment]
estimate_parameters_em and MAR now support batching. Examples can be found in test/parameters_tests.jl
