### ISSUE TITLE
[ProbabilisticCircuits] kmeans In em.jl 

### ISSUE THREAD

**Issue by nicoladimauro** [Juice-jl/ProbabilisticCircuits.jl#42]
In the clustering function the kmeans algorithm is called. However, as reported in the documentation the K-means clustering works on a d×n data matrix X where each column of X is a d -dimensional data point.
Hence, at line 55 the transpose of the data matrix should be passed to the algorithm. As it is the clustering procedure works on column side.

**Comment by MhDang** [comment]
Thanks for the bug reporting. 
Yes, we should pass the transpose of the data to the clustering algorithm, and also fix line 61.
