### ISSUE TITLE
Speedup em parameter learning 

### ISSUE THREAD

**Issue by liuanji** [Juice-jl/ProbabilisticCircuits.jl#44]
Sometimes `estimate_parameters_em` and `MAR` cannot fully utilize the GPU. Probably need to auto-tune the batch size or better distribute workload to CUDA kernels.

**Comment by khosravipasha** [comment]
This ishould be mostly resolved now (except the cases with lots of children or lots of parent)

**Comment by khosravipasha** [comment]
Solved in `cuda-refactor`
