### ISSUE TITLE
Separate circuit counters for parallel traversals/queries

### ISSUE THREAD

**Issue by RenatoGeh** [Juice-jl/ProbabilisticCircuits.jl#64]
Hi,

Currently Juice stores a unique counter for each node to mark them as visited during a traversal. As a consequence, traversing the same circuit (for perhaps different queries) in parallel is not allowed.

Could we optionally let the user supply a counter map instead so we can run several threads traversing the same circuit at the same time? If so, what would be the most Juice-idiomatic? Here's an example proposal out of the top of my head, where `query` is some query function (like `log_likelihood_per_instance` or `isdeterministic`).

```julia
c = ... # some circuit
V = Dict{ProbCircuit, UInt32}()
query(c, args; counter = V)
```

Thanks

**Comment by guyvdbroeck** [comment]
It makes sense to provide a function that is given the node, an integer `k`, increments the counter by `k`, and returns the previous value of the counter. The the default implementation can use the `counter` field in the node struct -- this will always be fastest --, but one can also use a `Dict` as in your example or a field in the struct pointed at by the node's data field.

**Comment by khosravipasha** [comment]
Yeah I think this could be very useful. Also, at the same time we can probably provide a more robust reset counter, https://github.com/Juice-jl/LogicCircuits.jl/issues/64. 

Another option might be an option to deep copy the same circuit for each thread, uses more memory but probably better for speed. Then user can decide between the tradeoffs.

**Comment by guyvdbroeck** [comment]
I changed the traversal infrastructure in https://github.com/Juice-jl/LogicCircuits.jl/commit/00177e3ad32972c49d6e5e7463e35528510dab70 so that it is now safe to traverse the circuit in parallel: each traversal uses its own `Dict`.
