### ISSUE TITLE
BlossomV to become optional dependency

### ISSUE THREAD

**Issue by khosravipasha** [Juice-jl/ProbabilisticCircuits.jl#65]
JuliaHub for BlossomV
https://juliahub.com/ui/Packages/BlossomV/akfpb/0.4.3?t=2.

Using https://github.com/JuliaPackaging/Requires.jl

This also fixes #3

**Comment by guyvdbroeck** [comment]
closed by https://github.com/Juice-jl/ProbabilisticCircuits.jl/commit/64c3004e1b8dd21c49170ce3ff3d48bf3b642b69
