### ISSUE TITLE
Remove `use_gpu` when `data` is available

### ISSUE THREAD

**Issue by guyvdbroeck** [Juice-jl/ProbabilisticCircuits.jl#73]
We currently need to synchronize between the device used for the bitcircuit, the data, and often a `use_gpu` flag. Standardize on always using `isgpu(data)` for this decision whenever the data is available; move the bitcircuit to the same device as the data, and remove the `use_gpu` flag. Don't repeat infrastructure to move things to the GPU, assume the outside user makes that decision by saying `togpu(data)` or not.

**Comment by khosravipasha** [comment]
Also related, we are using `reuse` for resuing memory for different batches, but not across epochs, might be good to change the high level API to make it easy to do.
