### ISSUE TITLE
Avoid scalar indexing on GPU in `init_expectations`

### ISSUE THREAD

**Issue by guyvdbroeck** [Juice-jl/ProbabilisticCircuits.jl#74]
The initializer for expectations on the GPU is doing scalar indexing on https://github.com/Juice-jl/ProbabilisticCircuits.jl/blob/fc0c3acb9f0eb54fc1a12baf62d0c427a265a16f/src/queries/expectation_bit.jl#L88
This ends up happening on the GPU if `ParamBitCircuitPair` is on the GPU; scalar indexing on the GPU is very slow and a bad idea! We should move the `BitCircuit` to CPU or keep it there when doing these scalar operations. Perhaps postpone moving `BitCircuit` to GPU until after the initializer is called.

**Comment by khosravipasha** [comment]
Wrote a cuda kernel to fix this 
https://github.com/Juice-jl/ProbabilisticCircuits.jl/commit/14fbf66a1674ceea1836a3fda69bec059b2578f7
